### ISSUE TITLE
rockylinux.org 4XX errors

### ISSUE THREAD

**Issue by GwendolynK** [rocky-linux/rockylinux.org#31]
### To Reproduce

17 urls on the Rocky Linux website return with 4XX errors. In the Expected Behavior section is a list with all the relevant URLs.

### Expected Behavior

```csv
Page URL,HTTP Code,Discovered
http://dl.rockylinux.org/vault/rocky/8.4/gluster9/,403,01 May 2024 (06:15 UTC)
http://dl.rockylinux.org/vault/rocky/8.4/storage/,403,01 May 2024 (06:15 UTC)
https://rockylinux.org/community-charter,404,01 May 2024 (06:15 UTC)
https://rockylinux.org/news/1,404,01 May 2024 (06:15 UTC)
https://rockylinux.org/news/chat.rockylinux.org,404,01 May 2024 (06:15 UTC)
https://rockylinux.org/news/docs.rockylinux.org,404,01 May 2024 (06:15 UTC)
https://rockylinux.org/news/forums.rockylinux.org,404,01 May 2024 (06:15 UTC)
https://rockylinux.org/news/rockylinux.org,404,01 May 2024 (06:15 UTC)
https://rockylinux.org/privacy-policy,404,01 May 2024 (06:15 UTC)
https://rockylinux.org/robots.txt,404,11 Jul 2023 (15:32 UTC)
https://rockylinux.org/rss.xml,404,01 May 2024 (06:15 UTC)
https://rockylinux.org/sitemap.xml,404,11 Jul 2023 (15:32 UTC)
https://rockylinux.org/sponsors,404,01 May 2024 (06:15 UTC)
https://wiki.rockylinux.org/en/team/development/Package_Error_Tracking,404,01 May 2024 (06:15 UTC)
https://wiki.rockylinux.org/team/development/Build_Order/Build_Pass_10_Failure,404,01 May 2024 (06:15 UTC)
https://wiki.rockylinux.org/team/development/Mock_Build_Howto,404,01 May 2024 (06:15 UTC)
https://wiki.rockylinux.org/team/development/Package_Error_Tracking,404,01 May 2024 (06:15 UTC)
```

[rockylinux.org_http_4xx_client_errors_20240503.csv](https://github.com/rocky-linux/rockylinux.org/files/15204401/rockylinux.org_http_4xx_client_errors_20240503.csv)

### Device

Desktop/Laptop

### Browser

Blink (Chromium)

### Operating System

All

**Comment by NeilHanlon** [comment]
Looked into this with Gwen a bit - 

* the dl.rockylinux.org and wiki.rockylinux.org entries are not applicable for this repository
* the `rockylinux.org/news/1` url - I think these were never meant to exist -- I see other entries in Google for /news/2, /news/3, etc. IMO, let's let these die, I don't know what they're supposed to reference. Same for the /news/docs.rockylinux.org etc.. they seem just like bad entries.
* [x] sitemap.xml is fixed
* [x] rss.xml fixed

@rocky-linux/web - I think we need to fix the following (i.e., add redirects or add content). robots.txt seems there, but empty -- please confirm if intentional.

* [ ] privacy-policy
* [ ] robots.txt* [ ] sponsors

**Comment by FoggyMtnDrifter** [comment]
The following will need redirects:

- /privacy-policy -> /legal/privacy
- /sponsors -> /about/sponsors

As for the robots.txt, I honestly don't even remember us setting that up on the old site. I can't seem to find it in the old repository. Perhaps that was something that was generated by Vercel?

**Comment by FoggyMtnDrifter** [comment]
There are likely more redirects needed here. I will go through a list of all pages and compare old vs. new URLs and will fix those. Would make more sense to knock them all out instead of finding them by chance.
